name: CI Diagnose
on: { workflow_dispatch: {}, push: { branches: [ ci-debug/** ] }, pull_request: {} }
permissions: { contents: read }

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dump GitHub context
        run: |
          echo "event: ${{ github.event_name }}"
          echo "ref:   ${{ github.ref }}"
          echo "sha:   ${{ github.sha }}"

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Python env
        run: |
          python --version
          which python

      - name: Tree + key files
        run: |
          ls -la
          echo "--- pyproject.toml ---"; [ -f pyproject.toml ] && sed -n '1,200p' pyproject.toml || echo "missing"
          echo "--- setup.cfg ---"; [ -f setup.cfg ] && sed -n '1,200p' setup.cfg || echo "missing"
          echo "--- requirements*.txt ---"; ls -1 requirements*.txt 2>/dev/null || echo "none"

      - name: Test discovery
        run: |
          find tests -maxdepth 2 -type f -name "*.py" 2>/dev/null || echo "no tests dir"

      - name: Import sanity
        env: { PYTHONPATH: ${{ github.workspace }} }
        run: |
          python - <<'PY' || true
mods = ["crapssim","crapssim_api"]
for m in mods:
    try:
        __import__(m); print("OK import:", m)
    except Exception as e:
        print("FAIL import:", m, "->", e)
PY
