name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tooling (best-effort)
        run: |
          python -m pip install -U pip
          pip install ruff pytest pytest-cov || true

      - name: Ruff (soft-fail at first)
        run: |
          ruff version || exit 0
          ruff check . || true

      - name: Run pytest if tests exist (soft)
        shell: bash
        run: |
          if ls tests/**/*.py tests/*.py 1>/dev/null 2>&1; then
            pytest -q || true
          else
            echo "No tests found; skipping."
          fi

      - name: Summary
        run: echo "CI completed without hard failures."
