name: Gauntlet / Stress

on:
  workflow_dispatch:
    inputs:
      runs:
        description: "Number of gauntlet runs"
        required: true
        default: "20"
  schedule:
    - cron: "0 7 * * *"   # daily 07:00 UTC

jobs:
  gauntlet:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest
      - name: Run stress tests (marked)
        run: pytest -q -m stress || true
      - name: Run gauntlet batch
        run: |
          R=${{ github.event.inputs.runs || 20 }}
          for i in $(seq 1 $R); do
            if [ -f tools/vxp_gauntlet.py ]; then python tools/vxp_gauntlet.py || true; fi
          done
      - name: Upload gauntlet artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gauntlet-${{ github.run_id }}
          path: |
            reports/vxp_gauntlet/**/*
            reports/vxp_stress/**/* 
          if-no-files-found: ignore
