name: Lint (Ruff)

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install ruff
        run: python -m pip install -U pip ruff
      - name: Ruff check (hard fail)
        run: ruff check .
      - name: Ruff format check (hard fail)
        run: ruff format --check .
