name: Mypy (advisory)
on: { push: {}, pull_request: {}, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install mypy
        run: |
          python -m pip install -U pip
          pip install mypy types-setuptools
      - name: Run mypy (advisory)
        shell: bash
        run: |
          rc=0
          [ -d "crapssim" ] && mypy crapssim || true
          [ -d "crapssim_api" ] && mypy crapssim_api || true
          exit 0
