name: Tests (Py3.9)
on: { push: {}, pull_request: {}, workflow_dispatch: {} }
permissions: { contents: read }

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.9' }

      - name: Install pytest (only)
        run: |
          python -m pip install -U pip
          pip install pytest

      - name: Discover tests
        id: disco
        shell: bash
        run: |
          if [ -d tests ] && ls tests/**/*.py tests/*.py >/dev/null 2>&1; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Run pytest (quiet first pass)
        if: steps.disco.outputs.found == 'true'
        id: run1
        env:
          PYTHONPATH: ${{ github.workspace }}
          PYTHONHASHSEED: '0'
        shell: bash
        run: |
          mkdir -p reports
          set +e
          pytest -q -m "not stress" > reports/pytest_quiet.log 2>&1
          echo "rc=$?" >> $GITHUB_OUTPUT
          exit 0

      - name: If failed, rerun first failing test verbosely
        if: steps.disco.outputs.found == 'true' && steps.run1.outputs.rc != '0'
        env:
          PYTHONPATH: ${{ github.workspace }}
          PYTHONHASHSEED: '0'
        shell: bash
        run: |
          echo "==== Python ===="; python --version; which python
          echo "==== Env ===="; echo "PYTHONPATH=${PYTHONPATH}"
          echo "==== Quiet log head ===="; sed -n '1,200p' reports/pytest_quiet.log || true
          echo "==== Verbose rerun ===="
          pytest -vv -x --maxfail=1 --lf -ra --durations=25 | tee reports/pytest_verbose.log

      - name: Upload pytest logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-logs-py39
          path: |
            reports/pytest_quiet.log
            reports/pytest_verbose.log

      - name: Fail job if tests failed
        if: steps.disco.outputs.found == 'true' && steps.run1.outputs.rc != '0'
        run: |
          echo "Tests failed. See artifacts for logs."
          exit 1

      - name: No tests found — pass
        if: steps.disco.outputs.found != 'true'
        run: echo "No tests found; passing."
