name: Tests (Py3.12)
on: { push: {}, pull_request: {}, workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  tests312:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install pytest
        run: |
          python -m pip install -U pip
          pip install pytest
      - name: Discover tests
        id: disco
        shell: bash
        run: |
          if [ -d tests ] && ls tests/**/*.py tests/*.py >/dev/null 2>&1; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi
      - name: Run pytest (Py3.12)
        if: steps.disco.outputs.found == 'true'
        env: { PYTHONPATH: ${{ github.workspace }}, PYTHONHASHSEED: '0' }
        run: pytest -q -m "not stress"
      - name: No tests found — pass
        if: steps.disco.outputs.found != 'true'
        run: echo "No tests found; passing."
