name: Workflow Lint
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: rhysd/actionlint@v1
        with:
          # fail on errors; warnings allowed
          args: -color

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          python -m pip install -U pip
          pip install yamllint
      - name: Lint .github/workflows
        run: |
          yamllint -f github -d "{extends: default, rules: {line-length: disable, truthy: disable}}" .github/workflows
